mode: debug
mysql:
  dsn: >-
    ${MYSQL_USERNAME}:${MYSQL_PASSWORD}@tcp(${MYSQL_HOST}:${MYSQL_PORT})/zeus?charset=utf8&parseTime=True&loc=Local
  pool:
    min: 5
    max: 20
redis:
  host: ${REDIS_HOST}:${REDIS_PORT}
  auth: ${REDIS_PASSWORD}
  pool:
    min: 3
    max: 20
jwt:
  key:
    private: keys/jwt_private_key.pem
    public: keys/jwt_public_key.pem
  expiresat: 3600*24*1
casbin:
  model:
    rule_0: config/casbin/rbac_model_0.conf
lang:
  types: zh-CN|en-US
  names: 简体中文|English
domain: bullteam.local